M1 Firestorm model
UoB-HPC/SimEng pull request #245
Opened 2022-09-01 15:33 UTC by tomhepworth

Contains my best performing config fire (m1_firestorm6.yaml from my documentation on branch `m1-dev`) and a port allocator class that aims to approximate the load balancing of the firestorm core's front-end.

2022-09-05 09:59 UTC, FinnWilkinson requested changes
Bit of confusion over `issued` and `deallocate` functions in the M1 port allocator

2022-09-05 09:59 UTC, FinnWilkinson commented on src/include/simeng/pipeline/M1PortAllocator.hh
> +  void deallocate(uint8_t port) override;
Do these functions do the same thing? Or just duplicated comments?

2022-09-05 09:59 UTC, FinnWilkinson commented on src/lib/pipeline/M1PortAllocator.cc
> +
What is the need for both functions if one simply calls the other?

2022-09-12 15:12 UTC, jj16791 approved these changes

2022-09-12 16:11 UTC, FinnWilkinson commented on src/include/simeng/pipeline/M1PortAllocator.hh
> +  void deallocate(uint8_t port) override;
IGNORE - Clarified by Jack

2022-09-12 16:11 UTC, FinnWilkinson commented on src/lib/pipeline/M1PortAllocator.cc
> +
IGNORE - Clarified by Jack

2022-09-12 16:11 UTC, FinnWilkinson approved these changes

2022-09-13 09:37 UTC, merged