Added support for correctly sharing process memory regions between threads.
UoB-HPC/SimEng pull request #301
Opened 2023-03-23 13:35 UTC by rahahahat

This PR contains the fix for the arm-clang issue in which threads belonging to the same group we're not sharing process memory regions correctly.

2023-03-24 11:01 UTC, FinnWilkinson requested changes

2023-03-24 11:01 UTC, FinnWilkinson commented on src/lib/OS/MemRegion.cc
> +    startAddr = startAddr >= mmapReg_->mmapPtr ? startAddr : mmapReg_->mmapPtr;
Could you add brackets around `startAddr >= mmapReg_->mmapPtr` for readability please

2023-03-24 11:35 UTC, rahahahat commented on src/lib/OS/SimOS.cc
> +#include <iomanip>
removed

2023-03-24 11:37 UTC, rahahahat commented on src/include/simeng/OS/MemRegion.hh
> +   * represents the same. */
Removed the extra comment as it was repetitive

2023-03-24 12:10 UTC, rahahahat commented on src/include/simeng/OS/MemRegion.hh
> +  uint64_t memSize_;
Sorry, the comment is misleading, `memSize` represents the entire size of the process image. I have renamed the variable and reworded the comment as well. Also as far as `getStackStart` and `getProcessImageSize` are concerned both return correct values. `getStackStart` should return `memSize` at it represents the bottom-most address of the entire process image, the bottom-most address of the process image is start of the stack region of the process image.

2023-03-24 12:13 UTC, rahahahat commented on src/lib/OS/MemRegion.cc
> +  return stackReg_.start;
done

2023-03-24 12:15 UTC, rahahahat commented on src/lib/OS/MemRegion.cc
> +    return heapReg_->brk;
done

2023-03-24 12:30 UTC, rahahahat commented on src/lib/OS/MemRegion.cc
> +    return heapReg_->brk;
This was a good spot, there was a small inconsistency in the logic. Adding the comment highlighted the problem I have fixed it now.

2023-03-24 17:35 UTC, jj16791 requested changes

2023-03-24 17:35 UTC, jj16791 commented on src/include/simeng/OS/MemRegion.hh
>    /** This constructor creates am empty MemRegion.*/
"creates an"

2023-03-27 13:47 UTC, jj16791 approved these changes

2023-03-27 13:56 UTC, FinnWilkinson approved these changes

2023-03-28 13:23 UTC, FinnWilkinson approved these changes

2023-03-28 13:23 UTC, merged