Memory overhaul test suite fix
UoB-HPC/SimEng pull request #310
Opened 2023-04-21 12:54 UTC by FinnWilkinson

2023-04-21 12:56 UTC, FinnWilkinson commented on src/lib/memory/MMU.cc
> +    request->setFault();
Can still send this directly to port recieve rather than going through memory

2023-04-24 09:39 UTC, rahahahat commented on src/include/simeng/arch/aarch64/Architecture.hh
> +  mutable uint64_t insnId_ = 0;
Please rename to `insIdCtr_` and refactor comment to reflect the same please

2023-04-24 09:44 UTC, rahahahat requested changes

2023-04-24 09:44 UTC, rahahahat commented on src/include/simeng/arch/riscv/Architecture.hh
> +  mutable uint64_t insnId_ = 0;
Same as https://github.com/UoB-HPC/SimEng/pull/310/files#r1175033476

2023-04-24 09:49 UTC, merged