SST compile fix on MacOS
UoB-HPC/SimEng pull request #338
Opened 2023-10-26 08:26 UTC by FinnWilkinson

On more recent versions of MacOS, and more specifically with more recent versions of Apple Clang, SST is unable to be compiled due to `unary_function` and `binary_function` types being depricated (since c++11) and now removed from Apple Clang v15. There is a compile flag which re-enabled these types and this has been added to `CMakeLists.txt` if the user is on MacOS.

These functions are only used in SST, and in more recent versions (i.e. SST v13) they have been replaced - so this issue may only be short term if SimEng's SST support is updated to version 13+

2023-10-27 00:53 UTC, tom91136 requested changes

2023-10-27 00:53 UTC, tom91136 commented on CMakeLists.txt
> +  add_compile_options(-D_LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY_FUNCTION)
I think we should use `add_compile_definitions(_LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY_FUNCTION)` which is designed for this exact use case.

2023-10-30 12:42 UTC, tom91136 submitted a review, later dismissed

2023-10-30 12:51 UTC, dANW34V3R reviewed
Is it worth adding a TODO to remove it later and some explanation of the how this has been updated for newer versions of SST that we don't support yet?

2023-10-31 11:11 UTC, JosephMoore25 commented
I agree with Dan. Looks like this is a temporary fix which can hopefully be removed once SST has been updated. Beyond that, looks good

2023-10-31 13:57 UTC, ABenC377 approved these changes

2023-10-31 15:43 UTC, FinnWilkinson commented
@dANW34V3R @JosephMoore25 TODO comment added. Please check

2023-10-31 15:44 UTC, JosephMoore25 approved these changes

2023-10-31 16:38 UTC, dANW34V3R requested changes

2023-10-31 16:38 UTC, dANW34V3R commented on CMakeLists.txt
> +# TODO: Remove one SST integration has updated to SST version 13 or later - the use of unary and binary functions are removed in later versions.
Minor typo, "one" -> "once"

2023-11-01 10:03 UTC, FinnWilkinson commented on CMakeLists.txt
> +# TODO: Remove one SST integration has updated to SST version 13 or later - the use of unary and binary functions are removed in later versions.
Fixed

2023-11-01 10:29 UTC, dANW34V3R approved these changes

2023-11-01 10:50 UTC, ABenC377 approved these changes

2023-11-01 11:50 UTC, JosephMoore25 approved these changes

2023-11-02 10:46 UTC, jj16791 approved these changes

2023-11-02 15:00 UTC, merged